// iconMap.js
import {
  FaHtml5,
  FaReact,
  FaCss3Alt,
  FaJava,
  FaPython,
  FaNodeJs,
  FaGitAlt,
  FaGithub,
  FaChrome,
  FaFigma,
  FaCode,
  FaCubes,
  FaProjectDiagram,
  FaSitemap,
  FaTools,
  FaTerminal,
  FaLayerGroup,
  FaVuejs,
} from "react-icons/fa";
import {
  SiJavascript,
  SiTailwindcss,
  SiTypescript,
  SiNextdotjs,
  SiMongodb,
  SiPostgresql,
  SiNetlify,
  SiGitlab,
  SiVite,
  SiExpress,
  SiGodotengine,
} from "react-icons/si";
import { GrDatabase } from "react-icons/gr";
import { TbApi, TbHierarchy3 } from "react-icons/tb";
import { MdGridOn } from "react-icons/md";
import { AiOutlineConsoleSql } from "react-icons/ai";

export const iconMap = {
  FaHtml5,
  FaReact,
  FaCss3Alt,
  FaJava,
  FaPython,
  FaNodeJs,
  FaGitAlt,
  FaGithub,
  FaChrome,
  FaFigma,
  FaCode,
  FaVuejs,
  FaCubes,
  FaProjectDiagram,
  FaSitemap,
  FaTools,
  SiJavascript,
  SiTailwindcss,
  SiTypescript,
  SiNextdotjs,
  SiMongodb,
  SiPostgresql,
  SiNetlify,
  SiGitlab,
  SiVite,
  SiExpress,
  SiGodotengine,
  SiApachenetbeanside: TbApi,
  SiSQL: AiOutlineConsoleSql,
  SiTiled: MdGridOn,
  FaTerminal,
  FaLayerGroup,
  TbHierarchy3,
};
